#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'beautifulBinaryString' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING b as parameter.
#

def beautifulBinaryString(b):
    # Write your code here
    ind = 0 
    count = 0
    
    while (ind <len(b)):
        if b[ind]=="0" and ind+2<len(b):
            if b[ind+1]=="1":
                
                if b[ind+2]=="0":
                    
                    count+=1
                    ind+=2
                    
                    
                
        ind+=1
    return(count)
                    
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    b = input()

    result = beautifulBinaryString(b)

    fptr.write(str(result) + '\n')

    fptr.close()
