#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'caesarCipher' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING s
#  2. INTEGER k
#

def caesarCipher(s, k):
    # Write your code here
    
    list_alpha = list(map(chr, range(97, 123)))
    s1=list(s.lower())
    s2=list(s)
    
    for i in range(len(s)):
        
        if s1[i] not in list_alpha:
            pass
        else:
            if list_alpha.index(s1[i])+k>=len(list_alpha):
                
                    
                s1[i] = list_alpha[((list_alpha.index(s1[i])+k)%len(list_alpha))]
              
            else:
                s1[i] = list_alpha[list_alpha.index(s1[i])+k]
        
                
                     
    for i in range (len(s1)):
        if s2[i].isupper():
            s1[i]=s1[i].upper()
    return(''.join(s1))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    s = input()

    k = int(input().strip())

    result = caesarCipher(s, k)

    fptr.write(result + '\n')

    fptr.close()
