#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'closestNumbers' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def quick_sort(arr): # i am sorting my array with quick sort algorithm
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort(left) + middle + quick_sort(right)

def closestNumbers(arr):
    # Write your code here
    arr = quick_sort(arr)
    #arr.sort()
    mapp = {}
    for i in range(len(arr)-1):
        if i==0:
            mini=arr[i+1]-arr[i]
            mapp[mini]=[arr[i],arr[i+1]]
        else:
            if arr[i+1]-arr[i]==mini:
                mapp[mini].append(arr[i])
                mapp[mini].append(arr[i+1])
            elif arr[i+1]-arr[i]<mini: 
                mini=arr[i+1]-arr[i]
                mapp.clear()
                mapp[mini]=[arr[i],arr[i+1]]
    return(mapp[mini])
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = closestNumbers(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
