#!/bin/python3

import math
import os
import random
import re
import sys
from itertools import repeat

#
# Complete the 'countingSort' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def countingSort(arr):
    # Write your code here
    liste = [0]*100
    for i in arr: 
        liste[i]+=1
    liste2=[]
    for i in range(len(liste)):
        if liste[i]>0:
            liste2.extend(repeat(i,liste[i]))
    return(liste2)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = countingSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
