#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'funnyString' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def funnyString(s):
    res= "Funny"
    # Write your code here

    r =s[::-1]
    print(r)

    for i in range (len(s)):
        print(s[i],ord(s[i]))
        if i!=(len(s))-1:
            if abs(ord(s[i+1])-ord(s[i]))!= abs(ord(r[i+1])-ord(r[i])):
                res= "Not Funny" 
                break
    return res    
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = funnyString(s)

        fptr.write(result + '\n')

    fptr.close()
