#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'hackerrankInString' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def hackerrankInString(s):
    # Write your code here
    liste=list("hackerrank")

    lists = list(s)
    emplist=[]
    
    for i in (liste):
        for j in range(len(lists)):
            if lists[j]==i:
                lists=lists[j+1:]
                emplist.append(i)
                break

    if emplist==liste:
        print(liste)
        print(emplist)
        return("YES")
    else:
        return("NO")

        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = hackerrankInString(s)

        fptr.write(result + '\n')

    fptr.close()
