#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'howManyGames' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER p
#  2. INTEGER d
#  3. INTEGER m
#  4. INTEGER s
#

def howManyGames(p, d, m, s):
    # Return the number of games you can buy
    numOfGames = 1
    cost = p
    dd= d
    while(cost<s ):
        if p<m:
            p=m
            cost+=p
        else: 
            if ((p-d)>=m):
                cost +=(p-d)
                p-=d
            else:
                p=m
                cost+=p
        print(p)
        numOfGames+=1
    if cost>s:
        numOfGames-=1
        
        
        
    
    return numOfGames
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    p = int(first_multiple_input[0])

    d = int(first_multiple_input[1])

    m = int(first_multiple_input[2])

    s = int(first_multiple_input[3])

    answer = howManyGames(p, d, m, s)

    fptr.write(str(answer) + '\n')

    fptr.close()
