#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'icecreamParlor' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER m
#  2. INTEGER_ARRAY arr
#

def icecreamParlor(m, arr):
    # Write your code here
    return_list=[]
    for i in range(len(arr)): 
        if arr[i]<m:
            return_list.append(i+1)
            print(return_list)
            for j in range(i+1,(len(arr))):
                if arr[j]+arr[i]==m:
                    print(return_list)
                    return_list.append(j+1)
                    break
                if j==len(arr)-1 and len(return_list)<2:
                    return_list=[]
                    break
        if len(return_list)==2:
            return(return_list)
            break
            
    
                

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        m = int(input().strip())

        n = int(input().strip())

        arr = list(map(int, input().rstrip().split()))

        result = icecreamParlor(m, arr)

        fptr.write(' '.join(map(str, result)))
        fptr.write('\n')

    fptr.close()
