#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#


def insertionSort1(n, arr):
    # Write your code here
    right = arr[-1]
    arr2=list(reversed(arr))
    for i in range(1,len(arr2)):
        if i==len(arr2)-1:
            if arr2[i]>right:
                arr2[i-1]=arr2[i]
                print(*list(reversed(arr2)))
                arr2[i]=right

                
            else:
                arr2[i-1]=right
            
            print(*list(reversed(arr2)))
            break
            
        else:            
            if arr2[i]>right:
                arr2[i-1]=arr2[i]
                print(*list(reversed(arr2)))#print the elements of list in one line 
            else:
                arr2[i-1]=right
                print(*list(reversed(arr2)))
                break
        
    
            

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
