#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'makingAnagrams' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING s1
#  2. STRING s2
#

def makingAnagrams(s1, s2):
    total_len = len(s1)+len(s2)
    sameChar = 0 
    lists1 = list(s1)
    lists2 = list(s2)
    for i in (lists1): 
        for j in (lists2):
            if i==j : 
                sameChar+=2
                
                
                lists2.remove(j)
                break
    return(total_len-sameChar)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s1 = input()

    s2 = input()

    result = makingAnagrams(s1, s2)

    fptr.write(str(result) + '\n')

    fptr.close()
