#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the maximumToys function below.
def maximumToys(arr, k):
     n = len(arr) 
     toplam = 0
     count = 0
     arr.sort()
     for i in arr: 
        if toplam+i <=k:
            toplam+=i
            count+=1
        else: 
            break
     return count
            
            
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    prices = list(map(int, input().rstrip().split()))

    result = maximumToys(prices, k)

    fptr.write(str(result) + '\n')

    fptr.close()
