#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'marsExploration' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def marsExploration(s):
    # Write your code here
    sos = "SOS"
    counter = 0
    for i in range(0,len(s),3):
        sos2=str(s[i]+s[i+1]+s[i+2])
        for j in range(3):
            if sos[j]!=sos2[j]:
                counter+=1
    return counter

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = marsExploration(s)

    fptr.write(str(result) + '\n')

    fptr.close()
