#!/bin/python3

import math
import os
import random
import re
import sys
import string

#
# Complete the 'pangrams' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def pangrams(s):
    # Write your code here
    alphabet= [char for char in string.ascii_lowercase]
    
    s=s.lower()
    for i in s:
        if i in alphabet:
            
            alphabet.remove(i)
            
        if len(alphabet)==0:
            break
    if len(alphabet)==0:
        return("pangram")
    else:
        return("not pangram")
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = pangrams(s)

    fptr.write(result + '\n')

    fptr.close()
