#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the makeAnagram function below.
def makeAnagram(a, b):
    sayac = 0 
    listA = [0]*26
    listB = [0]*26
    for i in a: 
        listA[ord(str(i))-ord('a')]+=1
    for j in b : 
        listB[ord(str(j))-ord('a')]+=1
    for i in range(len(listA)):
        sayac += abs(listA[i] - listB[i])
    return(sayac)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = input()

    b = input()

    res = makeAnagram(a, b)

    fptr.write(str(res) + '\n')

    fptr.close()
