#!/bin/python3

import math
import os
import random
import re
import sys
import string 

#
# Complete the 'theLoveLetterMystery' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def theLoveLetterMystery(s):
    # Write your code here
    first = 0 
    last =len(s)-1
    count= 0 
    for i in range(len(s)//2):
        if s[first]!=s[last]:
            firstPos = string.ascii_lowercase.index(s[first])
            lastPos = string.ascii_lowercase.index(s[last])
            count+=abs(firstPos-lastPos)
        first+=1
        last-=1
    return(count)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = theLoveLetterMystery(s)

        fptr.write(str(result) + '\n')

    fptr.close()
