#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeInWords' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. INTEGER h
#  2. INTEGER m
#

def timeInWords(h, m):
    # Write your code here
    list_of_nums = ['one', 'two', 'three', 'four', 'five', 'six', 'seven',
                   'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen',
                   'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen',
                   'nineteen','twenty','twenty one','twenty two','twenty three',
                   'twenty four','twenty five','twenty six','twenty seven',
                   'twenty eight','twenty nine' , 'thirty']
    if m < 30 : 
        if m == 15: 
            hour= "quarter past {}".format(list_of_nums[h-1])
        elif m==0:
            hour = "{} o' clock".format(list_of_nums[h-1])
        else: 
            if m==1:
                hour = "one minute past {}".format(list_of_nums[h-1])
                
            else : 
                hour = "{} minutes past {}".format(list_of_nums[m-1],list_of_nums[h-1])
                
    
    elif m==30:
        hour = "half past {}".format(list_of_nums[h-1])
    elif m==45 : 
        hour = "quarter to {}".format(list_of_nums[h])
    else :
        if m == 59 : 
             
            hour = "one minute to {}".format(list_of_nums[h])
        else:
            hour = "{} minutes to {}".format(list_of_nums[60-m-1],list_of_nums[h])
    
    return hour
    
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    h = int(input().strip())

    m = int(input().strip())

    result = timeInWords(h, m)

    fptr.write(result + '\n')

    fptr.close()
