#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countSort' function below.
#
# The function accepts 2D_STRING_ARRAY arr as parameter.
#

def countSort(arr):
    # Write your code here
    mapp = {}
    for i in range(len(arr)):
        
        if arr[i][0] not in mapp:
            if i<= (len(arr)/2-1):
                mapp[arr[i][0]]=["-"]
            else:
                mapp[arr[i][0]]=[arr[i][1]]
        else:
            if i<= (len(arr)/2-1):
                mapp[arr[i][0]].append("-")
            else:
                mapp[arr[i][0]].append(arr[i][1])
    #print(int(max(mapp)))
    our_output = ""
    for i in range(int(max(mapp))+1):
        
        if str(i) in mapp:
            for j in mapp[str(i)]:
                our_output+=str(j)
                our_output+=" "
    #print(mapp)
    print(our_output)

if __name__ == '__main__':
    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(input().rstrip().split())

    countSort(arr)
